apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local-storage-pv
spec:
  capacity:
    storage: 190Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/vdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocp4-hub.edwin.home
